appdev/appdev/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/code8", admin.site.urls),
    path("", include("main.urls")),
]

appdev/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("foglalas/", views.Idopontok.as_view(), name="foglalas"),
    path("foglalas/<str:honap>/<int:nap>", views.Idopontok2.as_view(), name="foglalas2"),
    path("foglalas/<str:honap>/<int:nap>/<str:idopont>", views.Reserve.as_view(), name="reserve"),
    path("error/", views.Error.as_view(), name="error"),
    path("test/", views.Test.as_view(), name="test"),
    path("thanks/", views.Thanks.as_view(), name="thanks"),
    path("uzenetx/", views.Uzenet.as_view(), name="uzenet"),
]

appdev/main/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    full_name = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.full_name


class Appointment(models.Model):
    honap = models.CharField(max_length=100)
    nap = models.IntegerField()
    nap_neve = models.CharField(max_length=20, default="hetfo")
    idopont = models.TimeField()
    free = models.BooleanField(default=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

    def reserve(self):
        self.free = False

    def __str__(self):
        return self.customer.full_name
    
class Service(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    filenev = models.CharField(max_length=50, default="macska.jpg")
        

class Message(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField(max_length=5000)

    def __str__(self):
        return self.name

    


    

appdev/main/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import View, TemplateView, ListView
from datetime import datetime
from django.http import HttpResponseRedirect

from .models import Appointment, Customer, Service, Message
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.contrib import messages
# Create your views here.

class Index(ListView):
    template_name = "main/index.html"
    queryset = Service.objects.all()


class Idopontok(ListView):

    template_name = "main/appointment.html"
    honapok = ["Január", "Február", "Március", "Április", "Május", "Június"]
    napok = ["Hétfő"]
    current_month = honapok[(datetime.now().month)-1]
    queryset = Appointment.objects.filter(free=True, honap=current_month).values("nap").distinct().order_by("nap")


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["month"] = self.current_month
        return context

class Idopontok2(View):

    def get(self, request, honap, nap):
        queryset = Appointment.objects.filter(free=True, honap=honap, nap=nap)
        appo = [i.idopont.strftime("%H:%M") for i in queryset]
        appo.sort()
        return render(request, "main/appointment2.html", {"object_list":appo, "honap":honap, "nap":nap})
    
class Reserve(View):

    def get(self, request, honap, nap, idopont):
        template = "main/book.html"
        return render(request, template, {"honap":honap,"nap":nap,"idopont":idopont})
    
    def post(self, request, honap, nap, idopont):
        full_name = request.POST["full_name"]
        email= request.POST["email"]

        form = Customer(full_name=full_name, email=email)
        form.save()

        message = render_to_string("main/email_temp.html", {
            "name":full_name,
            "honap":honap,
            "nap":nap,
            "idopont":idopont,
            'protocol': 'https' if request.is_secure() else 'http',
        })

        n_email = EmailMessage("foglalás", message, to=[email])
        n_email.content_subtype = "html"

        if n_email.send():
            print('Successful email sending')
        else:
            print('FAIL')
            return redirect("main:error")

        appo = Appointment.objects.get(honap=honap, nap=nap, idopont=idopont)
        appo.customer = form
        appo.reserve()
        appo.save()
        return HttpResponseRedirect(reverse("main:thanks"))
    

class Uzenet(View):

    def post(self, request):
        name = request.POST["name"]
        email = request.POST["email"]
        message = request.POST["uzenet"]

        new = Message(name=name, email=email, message=message)
        new.save()
        messages.success(request, "Sikeres üzenetküldés", extra_tags="text-center p-6 m-6 bg-green-500")
        return render(request, "main/index.html", {"uzenet":True})


class Error(TemplateView):
    template_name = "main/error.html"

class Test(TemplateView):
    template_name = "main/test.html"

class Thanks(TemplateView):
    template_name = "main/thanks.html"

appdev/main/templates/main/appointment.html
{% extends "main/base.html" %}

{% block title %}Időpontfoglalás{% endblock title %}

{% block content %}
<a href="/" class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
    <i class="fa-solid fa-house"></i>
</a>
<div class="container mx-auto mt-8 p-8">
    <h1 class="text-center m-6 p-6 text-5xl text-blue-900">{{month}}</h1>
    <h2 class="text-4xl font-bold mb-8 text-blue-900">Elérhető napok:</h1>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {% for appointment in object_list %}
            <a href="{% url 'main:foglalas2' month appointment.nap %}" class="rounded-lg overflow-hidden shadow-md p-4 hover:bg-white hover:text-blue-900 text-white text-xl bg-blue-900 w-[80%]">{{month}} {{appointment.nap}}</a>
        {% endfor %}
    </div>
    <div class="informacio mt-24">
        <h2 class="text-center bg-yellow-500 text-5xl p-8 rounded text-white">Nyitvatartás csak hétfőn és csütörtökön!</h2>
        <p class="p-4 m-2 text-sm md:text-lg italic">Társaságunk az alábbi egészségpénztárakkal áll szerződéses kapcsolatban:
            Allianz Egészség- és Önsegélyező Pénztár, Generali Egészség- és Önsegélyező Pénztár, MKB Egészség- és Önsegélyező Pénztár, OTP Országos Egészség- és Önsegélyező Pénztár, PRÉMIUM Egészségpénztár, Vasutas Egészség- és Önsegélyező Pénztár, Vitamin Egészségpénztár, Új Pillér Egészségpénztár, Patika Egészségpénztár.</p>
    </div>
</div>


{% endblock content %}

appdev/main/templates/main/appointment2.html
{% extends "main/base.html" %}
{% block title %}Időpontfoglalás{% endblock title %}

{% block content %}
<a href="/" class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
    <i class="fa-solid fa-house"></i>
</a>
<div class="container mx-auto mt-8 p-8">
    <h1 class="text-center m-6 p-6 text-5xl text-blue-900">{{honap}} {{nap}}</h1>
    <h2 class="text-4xl font-bold mb-8 text-blue-900">Elérhető időpontok:</h1>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {% for appointment in object_list %}
            <a href="{% url 'main:reserve' honap nap appointment %}" class="rounded-lg overflow-hidden shadow-md p-4 hover:bg-white hover:text-blue-900 text-white text-xl bg-blue-900 w-[80%]">{{appointment}}</a>
        {% endfor %}
    </div>
    <div class="informacio mt-24">
        <h2 class="text-center bg-yellow-500 text-5xl p-8 rounded text-white">Nyitvatartás csak hétfőn és csütörtökön!</h2>
        <p class="p-4 m-2 text-sm md:text-lg italic">Társaságunk az alábbi egészségpénztárakkal áll szerződéses kapcsolatban:
            Allianz Egészség- és Önsegélyező Pénztár, Generali Egészség- és Önsegélyező Pénztár, MKB Egészség- és Önsegélyező Pénztár, OTP Országos Egészség- és Önsegélyező Pénztár, PRÉMIUM Egészségpénztár, Vasutas Egészség- és Önsegélyező Pénztár, Vitamin Egészségpénztár, Új Pillér Egészségpénztár, Patika Egészségpénztár.</p>
    </div>
    
</div>


{% endblock content %}

appdev/main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    <!--w3css-->
    
    <!-- Tailwind -->
    
    <!-- MY CSS -->
    <link rel="stylesheet" href="{% static "main/css/styles.css" %}">
    <link rel="icon" type="image/x-icon" href="static/main/images/favicon.ico">
    <link rel="stylesheet" href="{% static "main/css/output.css" %}">

    <!-- GOOGLE FONTS-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap"
        rel="stylesheet">

    <!--Fontawsome-->
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

    <!-- Javascript-->
    <script defer src="{% static 'main/js/script.js' %}"></script>
    <script defer type="module" src="https://unpkg.com/ionicons@4.5.10-0/dist/ionicons/ionicons.esm.js"></script>

    {% block head %}{% endblock head %}
</head>
<body class="bg-gray-100 font-sans">
    {% block content %}
    {% endblock content %}
    

<footer class="bg-blue-900 p-12 mt-4" id="footer">
    <div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
        <div class="md:flex md:justify-between">
          <div class="mb-6 md:mb-0">
                <span class="self-center text-3xl font-semibold whitespace-nowrap text-white">Elérhetőségek:</span>
          </div>
          <div class="grid grid-cols-1 gap-2 sm:gap-3 sm:grid-cols-2 lg:grid-cols-3 text-center">
              <div>
                  <h2 class="mb-6 text-sm font-semibold text-white"><i class="fa-solid fa-phone"></i> +36 70 325 0310</h2>
              </div>
              <div>
                  <h2 class="mb-6 text-sm font-semibold text-white"><i class="fa-regular fa-envelope"></i> nagykovacsilaborszolgaltatas@gmail.com</h2>
              </div>
              <div>
                  <h2 class="mb-6 text-sm font-semibold text-white"><i class="fa-solid fa-location-dot"></i> Kossuth Lajos u. 33., Nagykovácsi</h2>
              </div>
          </div>
      </div>
      <hr class="my-6 border-white sm:mx-auto dark:border-white lg:my-8"/>
      <div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8 grid grid-cols-1 md:grid-cols-2 justify-items-center">
            <h1 class="text-white text-3xl text-center">Bármilyen kérdése van, bátran küldjön üzenetet!</h1>
            {% if uzenet %}
                <div class="text-3xl text-white">Sikeres üzenetküldés!</div><br>
                <i class="fa-solid fa-check text-green-500 bg-white text-5xl rounded p-6"></i>
            {% else %}
                <form class="text-center grid grid-cols-1 md:w-[50%]" action="{% url 'main:uzenet' %}" method="POST">
                    {% csrf_token %}
                    <input class="text-white border-b-2 border-white bg-blue-900 leading-tight focus:outline-none m-2 p-2" type="text" name="name" placeholder="Név">
                    <input class="text-white border-b-2 border-white bg-blue-900 leading-tight focus:outline-none m-2 p-2" type="email" name="email" placeholder="Email">
                    <textarea class="text-white border-2 border-white bg-blue-900 leading-tight focus:outline-none m-2 p-2" name="uzenet" placeholder="Üzenet" id="" cols="20" rows="7"></textarea>
                    <input type="submit" name="submit" class="m-2 p-2 text-white bg-blue-900 cursor-pointer border-2 hover:bg-blue-800 border-white text-2xl" value="Küldés" id="">
                </form>
            {% endif %}
      </div>
    </div>
    <p class="hidden top-[12%]"></p>
</footer>
</body>
</html>

appdev/main/templates/main/book.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Időpontfoglalás{% endblock title %}

{% block content %}

<div class="container mx-auto mt-8 p-8">
  <div class="grid grid-cols-1 md:grid-cols-2">
    <h1 class="text-4xl font-bold mb-8 text-blue-900">Az ön időpontja: <span>{{honap}} {{nap}}. {{idopont}}</span></h1>
    <form class="w-full max-w-sm" method="POST">
        {% csrf_token %}
        <div class="md:flex md:items-center mb-6">
          <div class="md:w-1/3">
            <label class="block text-blue-900 font-bold md:text-right mb-1 md:mb-0 pr-4" for="full_name">
              Teljes név:
            </label>
          </div>
          <div class="md:w-2/3">
            <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-500" name="full_name" type="text" placeholder="Kis János">
          </div>
        </div>
        <div class="md:flex md:items-center mb-6">
          <div class="md:w-1/3">
            <label class="block text-blue-900 font-bold md:text-right mb-1 md:mb-0 pr-4" for="email">
              Email cím:
            </label>
          </div>
          <div class="md:w-2/3">
            <input class="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-red-500" id="email" name="email" type="email" placeholder="kisjanos1965@gmail.com">
          </div>
        </div>
        <div class="md:flex md:items-center">
          <div class="md:w-1/3"></div>
          <div class="md:w-2/3">
            <input class="cursor-pointer shadow hover:bg-red-700 text-white bg-red-400 focus:shadow-outline focus:outline-none font-bold py-2 px-4 rounded" type="submit" value="Foglalás">
          </div>
        </div>
    </form>
  </div>
  <div class="p-6 m-6">
    <i>Amennyiben ön nem rendelkezik email címmel, kérjük telefonon foglalja le időpontját.</i>
    <i>Vérvételi napokon kérjük csak rendelési idő után telefonáljanak, 
          mert nem tudjuk felvenni a telefont. Köszönjük megértésüket!</i>
  </div>
  <!--<img class="w-[50%] m-auto rounded" src="{% static 'main/images/viragok.jpg' %}" alt=""> -->
</div>

{% endblock content %}

appdev/main/templates/main/email_temp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 0; background-color: #f4f4f4; color: #333;">

    <div style="max-width: 600px; margin: 20px auto; background-color: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);">
        <h1 style="color:rgb(30, 58, 138); text-align:center;">Nagykovácsi laborszolgáltatás</h1>
        <p>Tisztelt {{name}},</p>
        <p>Köszönjük a foglalását!</p>        
        <p>Az ön időpontja: {{honap}} {{nap}} {{idopont}}</p>
        <p>Bármilyen kérdése van keressen minket bátran az alábbi telefonszámon:</p><br>
        <p>+36 70 325 0310</p>

        <p>
            <a href="https://nagykovacsilaborszolgaltats.hu" style="background-color:rgb(30, 58, 138); color:white; cursor:pointer; text-decoration:none; padding:1rem;">Vissza a weboldalra</a>
        </p>
    </div>
</body>
</html>

appdev/main/templates/main/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Nem tudtuk elküldeni az emailt.</h1>
</body>
</html>

appdev/main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Nagykovácsi laborszolgáltatás | vérvétel{% endblock title %}

{% block content %}
<header class="bg-white md:fixed md:top-0 md:left-0 md:w-full">
    <nav class="flex justify-between items-center w-[92%] mx-auto">
      <div>
          <a href="/"><img class="cursor-pointer h-32" src="{% static 'main/images/nkl-logo.png' %}" alt="logo"></a>
      </div>
      <div
          class="nav-links duration-500 md:static absolute bg-white md:min-h-fit min-h-[60vh] left-0 top-[-100%] md:w-auto w-full flex px-5 opacity-90">
          <ul class="flex md:flex-row flex-col md:items-center md:gap-[4vw] gap-8 font-semibold text-blue-900">
              <li>
                  <a class="hover:text-gray-500" href="#arak">Árazás</a>
              </li>
              <li>
                  <a class="hover:text-gray-500" href="#vizsgalatok">Vizsgálatok</a>
              </li>
              <li>
                  <a class="hover:text-gray-500" href="#footer">Kapcsolat</a>
              </li>
              <li>
                  <a class="hover:bg-red-700 text-white bg-red-400 p-4" href="{% url 'main:foglalas' %}">Időpontfoglalás</a>
              </li>
          </ul>
      </div>
      <div class="flex items-center gap-6">
          <ion-icon onclick="onToggleMenu(this)" name="menu" class="text-3xl cursor-pointer md:hidden"></ion-icon>
      </div>
    </nav>
</header>

<div class="w-full h-full grid grid-cols-2 gap-2 big-image p-1 md:p-24 md:mt-16">
    
    <div class="text-center grid content-center text-xl content-frame rounded p-3">
        <h2 class="text-blue-900 md:text-5xl p-2 mb-1">Nagykovácsi</h2>
        <p class="text-red-500 md:text-4xl">Laborszolgáltatás</p>
        <div class="hidden md:block mt-3">
            <h3 class="text-xl text-blue-900">gyermekek és felnőttek teljes körű laborvizsgálata</h3>
        </div>
    </div>
    <div class="text-center">
        <h3 class="md:text-3xl text-lg mb-4 text-blue-900">Nyitvatartási idő:</h3>
        <div class="bg-yellow-500 text-bold text-sm md:text-lg md:w-[50%] m-auto p-4 mb-6 text-white">Hétfő: 6:30 - 10:00</div>
        <div class="bg-yellow-500 text-bold text-sm md:text-lg md:w-[50%] m-auto p-4 mb-6 text-white">Csütörtök: 6:30 - 10:00</div>
        <a href="{% url 'main:foglalas' %}" class="mt-4 bg-red-400 hover:bg-red-600 text-white font-bold py-2 px-4 rounded hidden md:inline-block"><i class="fa-solid fa-calendar-check"></i> Időpontfoglalás</a>
    </div>
    <div class="text-center">
        
    </div>
</div>

<div class="text-center">
    <a href="{% url 'main:foglalas' %}" class="mt-4 inline-block bg-red-400 hover:bg-red-600 text-white font-bold py-2 px-4 rounded md:hidden"><i class="fa-solid fa-calendar-check"></i> Időpontfoglalás</a>
</div>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li><div id="alert-border-3" class="flex items-center p-4 mb-4 text-green-800 border-t-4 border-green-300 bg-green-100 justify-center" role="alert">
            <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
            </svg>
            <div class="ms-3 text-sm font-medium">
            {{message}}
            </div>
        </div></li>
        {% endfor %}
    </ul>
{% endif %}
<main class="w-[90%] m-auto">
    <h2 class="text-4xl font-bold text-center mt-8 mb-8 text-blue-900" id="akt">Miért válasszon minket?</h2>
    <div class="aktualitasok grid grid-cols-1 md:grid-cols-2 justify-items-center gap-3 w-[80%] m-auto">
        <div class="bg-white p-6 rounded-lg shadow-md grid grid-rows-2 justify-items-center text-blue-900"><i class="fa-solid fa-stopwatch text-6xl mb-4"></i> <span class="text-2xl">Várakozás nélkül, beutaló nem szükséges</span></div>
        <div class="bg-white p-6 rounded-lg shadow-md grid grid-rows-2 justify-items-center text-blue-900"><i class="fa-solid fa-business-time text-6xl mb-4"></i> <span class="text-2xl">Az eredmények többsége 1-2 munkanapon belül elkészül</span></div>
        <div class="bg-white p-6 rounded-lg shadow-md grid grid-rows-2 justify-items-center text-blue-900"><i class="fa-solid fa-envelope text-6xl mb-4"></i> <span class="text-2xl">Leleteit az Ön e-mail címére továbbítjuk</span></div>
        <div class="bg-white p-6 rounded-lg shadow-md grid grid-rows-2 justify-items-center text-blue-900"><i class="fa-solid fa-fire text-6xl mb-4"></i> <span class="text-2xl">Vizsgálati palettánk a hazai szolgáltatók közül a legszélesebb</span></div>
    </div>

    <section class="container mx-auto p-4">
        <h2 class="text-4xl font-bold text-center mb-8 mt-8 text-blue-900" id="vizsgalatok">Vizsgálatok</h2>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {% for service in object_list %}
            <div class="bg-white rounded-lg overflow-hidden shadow-md">
                <img src="static/main/images/{{service.filenev}}" alt="Service 1" class="w-full h-40 object-cover">
                <div class="p-4">
                    <h3 class="text-xl font-semibold mb-2 text-blue-900">{{service.name}}</h3>
                    <p class="text-gray-600">{{service.description}}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>

    <section class="mb-6">
        <h2 class="text-4xl font-bold text-center mb-8 mt-8 text-blue-900" id="arak">Árak</h2>
        <div class="grid grid-cols-1 gap-2 text-center text-white text-xl md:text-3xl justify-items-center">
            <div class="bg-yellow-500 md:w-[50%] p-3">Mintavétel: <span>3200FT</span></div>
            <div class="bg-yellow-500 md:w-[50%] p-3">Mintaátvétel: <span>1000FT</span></div>
        </div>

    </section>
</main>

{% endblock content %}

appdev/main/templates/main/test.html
{% extends "main/base.html" %}

appdev/main/templates/main/thanks.html
{% extends "main/base.html" %}

{% block title %}Sikeres foglalás!{% endblock title %}

{% block content %}
<div class="text-xl text-center p-6 m-6 text-blue-900">
    <h1 class="text-2xl m-6">Foglalását rögzítettük!</h1>
    <h2>Emlékeztetőül küldtünk önnek egy email-t a megadott email címre.</h2>
    <p>Amennyiben le szertné mondani időpontját azt telefonon megteheti az alábbi számon:</p>
    <p>06 70 325 0310</p>
</div>
<a class="bg-blue-900 text-white p-4 m-6 hover:text-blue-900 hover:bg-white" href="{% url 'main:index' %}">Vissza a főmenübe</a>
{% endblock content %}